name: Build and release

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Download and copy header
      run: |
        wget https://github.com/YIsoda/lapack-build/releases/download/v0.1.0/lapack-build-release.zip
        unzip lapack-build-release.zip
        cp artifacts/*.h console-devel-2.0.1/src/dataProcess
    - name: Set DLLs
      run: |
        mkdir lib
        cp artifacts/*.dll console-devel-2.0.1/lib
    - name: Build
      run: |
        docker run --rm -v console-devel-2.0.1:/var/build darkmattercoder/qt-build:latest build /var/build/src/nmrProcess/nmrProcess.pro
        
    - name: Show build result
      run: ls console-devel-2.0.1/build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build_results
        path: console-devel-2.0.1/build
