name: Build and release

on: 
  push:
    branches: __dummy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Download and copy header
      run: |
        wget https://github.com/YIsoda/lapack-build/releases/download/v0.1.0/lapack-build-release.zip
        unzip lapack-build-release.zip
        ls
        ls ${GITHUB_WORKSPACE}
        cp artifacts/*.h ${GITHUB_WORKSPACE}/src/dataProcess
    - name: Set DLLs
      run: |
        mkdir lib
        cp artifacts/*.dll ${GITHUB_WORKSPACE}/lib
    - name: Build
      run: |
        sudo docker run --rm -u $UID -v ${GITHUB_WORKSPACE}:/var/build darkmattercoder/qt-build:latest build /var/build/src/nmrProcess/nmrProcess.pro -spec win32-x-g++
        
    - name: Show build result
      run: ls ${GITHUB_WORKSPACE}/build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: build_results
        path: ${GITHUB_WORKSPACE}/build
